default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host:  <%= Rails.application.credentials.development.postgres.host %>
  database: <%= Rails.application.credentials.development.postgres.database %>
  port:  <%= Rails.application.credentials.development.postgres.port %>
  username:  <%= Rails.application.credentials.development.postgres.username %>
  password: <%= Rails.application.credentials.development.postgres.password %>

test:
  <<: *default
  database: <%= Rails.application.credentials.test.postgres.database %>

production:
  <<: *default
  database: <%= Rails.application.credentials.production.postgres.database %>
  username: <%= Rails.application.credentials.production.postgres.username %>
  password: <%= Rails.application.credentials.production.postgres.password %>
